import { Router } from 'express';
import { protect } from '../middlewares/authMiddleware.js';
import * as classController from '../controllers/classController.js';
const router = Router();
router.use(protect);
router.get('/', classController.getClasses);
router.post('/', classController.createClass);
router.put('/:id', classController.updateClass);
router.delete('/:id', classController.deleteClass);
router.get('/bookings/list', classController.getBookings);
router.post('/bookings', classController.createBooking);
export default router;
